sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    bucket-name: sky-take-out-ame
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
